In [5]:
!pip install scikit-learn

In [6]:
# 순서대로 전처리 -> 모델의 판별
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np

cancer = load_breast_cancer()
df = pd.DataFrame(cancer.data, columns=cancer.feature_names)
df['label'] = cancer.target

In [7]:
df.head() # 30개의 특성과 label 0, 1 종속변수

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  label  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [8]:
df.iloc[:, :-1] # X
df.iloc[:, -1] # y

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: label, Length: 569, dtype: int64

In [9]:
len(df.columns)

31

In [10]:
# 데이터 수집 -> 전처리 -> 모델 학습 -> 평가 -> 앞의과정에서 부족한 부분 재수행하면서 모델의 추론결과를 높이는
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# 데이터를 train, test 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :-1], df.iloc[:, -1], test_size=0.2, random_state=121)

# 스케일링
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

# PCA
pca = PCA(n_components=2)
pca.fit(X_train_std)
X_train_std_pca = pca.transform(X_train_std)
X_test_std_pca =  pca.transform(X_test_std)

# 모델 생성
lr_clf = LogisticRegression()

# 학습
lr_clf.fit(X_train_std_pca, y_train)

# 성능측정
lr_clf.score(X_test_std_pca, y_test)

# 추론
# lr_clf.predict(np.array([[ 2.25274954, -2.77098469]]))

# 모델의 하이퍼 파라미터를 GridSearchCV 로 찾거나
# 모델을 서빙 -> Scaler -> PCA -> 모델

0.9912280701754386

In [11]:
lr_clf.score(X_test_std_pca, y_test)

0.9912280701754386

In [12]:
X_test_std_pca[0]

array([ 2.25274954, -2.77098469])

In [13]:
y_test.values[0]

0

In [14]:
# 데이터 수집 -> 전처리 -> 모델 학습 -> 평가 -> 앞의과정에서 부족한 부분 재수행하면서 모델의 추론결과를 높이는

# # 모델을 서빙 -> Scaler -> PCA -> 모델
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
# make_pipeline이라는 함수로 Pipeline 객체를 통해 전체 과정을 하나의 클래스에 담습니다.
from sklearn.pipeline import make_pipeline

# 데이터를 train, test 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :-1], df.iloc[:, -1], test_size=0.2, random_state=121)

# 객체 만들기
pipeline_lr = make_pipeline(StandardScaler(), PCA(n_components=2),  LogisticRegression())

# 학습
pipeline_lr.fit(X_train, y_train)

# # 성능측정
pipeline_lr.score(X_test, y_test)

# 추론
pipeline_lr.predict(np.array([[1.845e+01, 2.191e+01, 1.202e+02, 1.075e+03, 9.430e-02, 9.709e-02,
       1.153e-01, 6.847e-02, 1.692e-01, 5.727e-02, 5.959e-01, 1.202e+00,
       3.766e+00, 6.835e+01, 6.001e-03, 1.422e-02, 2.855e-02, 9.148e-03,
       1.492e-02, 2.205e-03, 2.252e+01, 3.139e+01, 1.456e+02, 1.590e+03,
       1.465e-01, 2.275e-01, 3.965e-01, 1.379e-01, 3.109e-01, 7.610e-02]]))


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0])

In [15]:
pipeline_lr

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('pca', PCA(n_components=2)),
                ('logisticregression', LogisticRegression())])

In [16]:
X_test.iloc[0, :].values

array([1.845e+01, 2.191e+01, 1.202e+02, 1.075e+03, 9.430e-02, 9.709e-02,
       1.153e-01, 6.847e-02, 1.692e-01, 5.727e-02, 5.959e-01, 1.202e+00,
       3.766e+00, 6.835e+01, 6.001e-03, 1.422e-02, 2.855e-02, 9.148e-03,
       1.492e-02, 2.205e-03, 2.252e+01, 3.139e+01, 1.456e+02, 1.590e+03,
       1.465e-01, 2.275e-01, 3.965e-01, 1.379e-01, 3.109e-01, 7.610e-02])

In [17]:
# # 모델의 하이퍼 파라미터를 GridSearchCV 로 찾거나

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# 파이프라인 생성 (각 스텝을 명시적으로 정의)
pipe = Pipeline([
    ('scaler', StandardScaler()),  # 스케일링
    ('pca', PCA()),  # PCA 적용
    ('logistic', LogisticRegression())  # 로지스틱 회귀 모델
])

# 하이퍼파라미터 그리드 정의
param_grid = {
    'pca__n_components': [2, 3, 4, 5, 6, 7], # 객체명__하이퍼파라미터명
    'logistic__C': [0.001, 0.01, 0.1, 1, 10, 100],  # C 값
}

# GridSearchCV 객체 생성
grid_search = GridSearchCV(pipe, param_grid, cv=5, scoring='accuracy', verbose=True)

# 학습 데이터로 최적의 하이퍼파라미터 찾기
grid_search.fit(df.iloc[:, :-1], df.iloc[:, -1])

# 최적의 하이퍼파라미터와 점수 출력
print("Best parameters:", grid_search.best_params_)
print("Best accuracy:", grid_search.best_score_)
pd.DataFrame(grid_search.cv_results_)


Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best parameters: {'logistic__C': 10, 'pca__n_components': 5}
Best accuracy: 0.9736686849868033


mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.009242      0.000937         0.003173        0.000255   
1        0.009168      0.000423         0.003066        0.000155   
2        0.008847      0.000306         0.002984        0.000152   
3        0.013142      0.003300         0.003810        0.000954   
4        0.010002      0.001346         0.003288        0.000466   
5        0.011297      0.004414         0.003538        0.000904   
6        0.014993      0.000557         0.005006        0.000717   
7        0.013940      0.001237         0.005220        0.001010   
8        0.013654      0.001167         0.004682        0.000638   
9        0.012605      0.000618         0.004415        0.000344   
10       0.024688      0.005731         0.007385        0.003610   
11       0.039140      0.010901         0.014269        0.006834   
12       0.028110      0.009088         0.006715        0.003100   
13       0.034198      0.012258         0.012032        0.004942   
14       0.036932      0.012241         0.008263        0.002519   
15       0.029979      0.006516         0.015934        0.005947   
16       0.062776      0.024381         0.012828        0.009737   
17       0.040904      0.008227         0.014295        0.006068   
18       0.037888      0.021381         0.012547        0.009823   
19       0.038454      0.013159         0.013679        0.008760   
20       0.034324      0.002654         0.014084        0.006810   
21       0.049450      0.012998         0.012940        0.006140   
22       0.042025      0.015313         0.022535        0.009349   
23       0.037837      0.004494         0.016712        0.005851   
24       0.026669      0.008099         0.009579        0.005778   
25       0.014030      0.001539         0.007742        0.005420   
26       0.021753      0.009460         0.009314        0.004566   
27       0.013139      0.000559         0.004793        0.001285   
28       0.020071      0.006672         0.005445        0.002041   
29       0.015021      0.002473         0.007265        0.003708   
30       0.028543      0.012450         0.007606        0.004114   
31       0.023505      0.009161         0.005249        0.001896   
32       0.015649      0.003319         0.006954        0.003914   
33       0.018191      0.008235         0.005530        0.001950   
34       0.035854      0.013251         0.005488        0.002015   
35       0.022232      0.010513         0.007019        0.003314   

    param_logistic__C  param_pca__n_components  \
0               0.001                        2   
1               0.001                        3   
2               0.001                        4   
3               0.001                        5   
4               0.001                        6   
5               0.001                        7   
6               0.010                        2   
7               0.010                        3   
8               0.010                        4   
9               0.010                        5   
10              0.010                        6   
11              0.010                        7   
12              0.100                        2   
13              0.100                        3   
14              0.100                        4   
15              0.100                        5   
16              0.100                        6   
17              0.100                        7   
18              1.000                        2   
19              1.000                        3   
20              1.000                        4   
21              1.000                        5   
22              1.000                        6   
23              1.000                        7   
24             10.000                        2   
25             10.000                        3   
26             10.000                        4   
27             10.000                        5   
28             10.000                

In [ ]:
#데이터 전처리, 차원 축소, 모델 선택, 하이퍼파라미터 튜닝 등 머신러닝의 전반적인 워크플로우를 모방해보았다.